# Exposure All EndPoints In Web
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"
  # Exposure Health Info
  endpoint:
    health:
      show-components: always

# Range hello.springactuator.controller package debug level
logging:
  level:
    hello.springactuator.controller: debug
