# Exposure All EndPoints In Web
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"
  # Exposure Health Info
  endpoint:
    health:
      show-components: always

