# Exposure All EndPoints In Web
management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true

  server:
    port: 9292

  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"
  # Exposure Health Info
  endpoint:
    health:
      show-components: always

# Range hello.springactuator.controller package debug level
logging:
  level:
    hello.springactuator.controller: debug
